spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/medical?useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  jackson:
    default-property-inclusion: non_empty