spring:
  datasource:
    url: jdbc:mysql://134.175.124.131:37258/medical?useSSL=false&characterEncoding=utf-8
    username: root
    password: 1qaz@WSX
  jpa:
    properties:
      hibernate:
        dialect: com.medical.configuration.MysqlConfiguration
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  jackson:
    default-property-inclusion: non_empty
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES